### ISSUE TITLE
Protocols for ChatMessage, ChatUser

### ISSUE THREAD

**Issue by kinoroy** [EnesKaraosman/SwiftyChat#1]
Have you considered using protocols for ChatMessage and ChatUser instead of structs?

A lot of the time, we already have our own domain objects/structs to represent a message or user and it would be nice if we could just extend those objects to conform to a protocol rather than having to convert to a new object. Additionally, the ChatMessage and ChatUser structs both initialize their own UUID which can't be changed, however we have our own IDs from our backend to identify a user/message that we want to use. 

Protocols is how MessageKit does it and since the README says you took inspiration from MessageKit, this might have been an intentional decision that you made to not go the protocol route but anyways, cool library and thought I would suggest something!

**Comment by EnesKaraosman** [comment]
Thanks for your suggestion, I’ll consider making those changes.

**Comment by EnesKaraosman** [comment]
Requested changes made with the version `1.0.0` thanks for feedback again. If you see a problem do not hesitate to inform again. Also contributions are welcomed.
