### ISSUE TITLE
Custom Cell shape

### ISSUE THREAD

**Issue by kele82** [EnesKaraosman/SwiftyChat#11]
Hi Enes,

First tnx for the great library.
How can I change cell shape?
I need the cell to look like in Viber where only one of the corners isn't rounded.
Since CommonViewStyle protocol has only cornerRadius as CGFloat, I don't see a way to change the shape of the cell.

**Comment by EnesKaraosman** [comment]
Hi, unfortunately not supported at the moment, you need to draw custom shape (need to fork and do your changes)
