### ISSUE TITLE
quick reply 

### ISSUE THREAD

**Issue by seniorAyman** [EnesKaraosman/SwiftyChat#12]
hi,
what if I want not to disable the selected choice after quick reply ?
regards

**Comment by EnesKaraosman** [comment]
Hi,

Visit [this](https://github.com/EnesKaraosman/SwiftyChat/blob/master/Sources/SwiftyChat/MessageCells/QuickReplyCell.swift) file, cancel `isDisabled` related parts & you're good to go.

For sure you need to fork the repo to have your own changes..
