### ISSUE TITLE
Scroll down when receiving messages

### ISSUE THREAD

**Issue by eriscoand** [EnesKaraosman/SwiftyChat#24]
Hello! First of all, your code is helping me alot on one of my projects tyvm!

I have implemeted a chat that send a message to server and a bot answers. But when I receive the answer the chat don't scroll down:

I'm doing it like this=>

            .onReceive(chatViewModel.$messages, perform: { messages in
                self.messages = messages
            })

Is there a way to refresh the view?

Tyvm!!

**Comment by EnesKaraosman** [comment]
Sure you can use scrollToBottom parameter on chatView constructor , set it to true when you want, see example project as well

**Comment by eriscoand** [comment]
I'm using SwiftyChat 2.0.0 and there is no scrollToBottom() on chatView constructor. On your Advanced example scrollToBottom is defined but never used :(

**Comment by EnesKaraosman** [comment]
Thx, @eriscoand I updated readme as well

```swift
@State private var scrollToBottom = false
@State private var messages: [MockMessages.ChatMessageItem] = [] // for quick test assign MockMessages.generatedMessages()

// ChatMessageItem & ChatUserItem is a sample objects/structs 
// that conforms `ChatMessage` & `ChatUser` protocols.
ChatView<MockMessages.ChatMessageItem, MockMessages.ChatUserItem>(
    messages: $messages,
    scrollToBottom: $scrollToBottom
) {
    // InputView here, continue reading..
}
// ▼ Required
.environmentObject(
    // All parameters initialized by default, 
    // change as you want.
    ChatMessageCellStyle()
)
.onReceive(
    messages.debounce(for: .milliseconds(650), scheduler: RunLoop.main),
    perform: { _ in
        scrollToBottom = true
    }
)
...
...
```

**Comment by eriscoand** [comment]
Awesome! Tyvm!

**Comment by seniorAyman** [comment]
**when I added this part**

.onReceive(
    messages.debounce(for: .milliseconds(650), scheduler: RunLoop.main),
    perform: { _ in
        scrollToBottom = true
    }
)

**I got a lot of errors**
Cannot call value of non-function type 'Binding<Subject>'
Cannot infer contextual base in reference to member 'milliseconds'
Referencing subscript 'subscript(dynamicMember:)' requires wrapper 'Binding<[MockMessages.ChatMessageItem]>'
Insert '$'
Value of type '[MockMessages.ChatMessageItem]' has no dynamic member 'debounce' using key path from root type '[MockMessages.ChatMessageItem]'

please advise
regards
