### ISSUE TITLE
scrollToBottom using onRecieve

### ISSUE THREAD

**Issue by seniorAyman** [EnesKaraosman/SwiftyChat#25]
when I added this part

.onReceive(
messages.debounce(for: .milliseconds(650), scheduler: RunLoop.main),
perform: { _ in
scrollToBottom = true
}
)

I got a lot of errors
Cannot call value of non-function type 'Binding'
Cannot infer contextual base in reference to member 'milliseconds'
Referencing subscript 'subscript(dynamicMember:)' requires wrapper 'Binding<[MockMessages.ChatMessageItem]>'
Insert '$'
Value of type '[MockMessages.ChatMessageItem]' has no dynamic member 'debounce' using key path from root type '[MockMessages.ChatMessageItem]'

please advise
regards

**Comment by EnesKaraosman** [comment]
try using with `$messages.debounce...`

**Comment by seniorAyman** [comment]
now the errors become like this

Cannot call value of non-function type 'Binding<Subject>'
Cannot infer contextual base in reference to member 'milliseconds'
Value of type 'Binding<[MockMessages.ChatMessageItem]>' has no dynamic member 'debounce' using key path from root type '[MockMessages.ChatMessageItem]'

**Comment by seniorAyman** [comment]
@EnesKaraosman
