### ISSUE TITLE
How do you extend Message Kinds?

### ISSUE THREAD

**Issue by nikans** [EnesKaraosman/SwiftyChat#26]
Hello. Since ChatMessageKind is a enum, and does not contain any .custom option either, how do you suppose to add new messages kinds?

**Comment by EnesKaraosman** [comment]
Hi @nikans , yes in current implementation we don't have custom message support but it'd be possible if we add new message kind `.custom(Any)` and we can add custom message method maybe on ChatView to bring UI & Logic together , so any contribution would be good 😊 , I added custom message support in my [Flutter version](https://github.com/EnesKaraosman/swifty_chat) of this chat package but could not save time to impl. in SwiftUI

**Comment by nikans** [comment]
Thanks, I'll keep in mind.

**Comment by EnesKaraosman** [comment]
@LeonardMaetzner 's MR is merged and we've released version 2.3.0 . You can keep enjoying!! @nikans .

Thanks for your feedbacks and contributions.
