### ISSUE TITLE
Chat view doesn't scroll on keyboard open / input

### ISSUE THREAD

**Issue by nikans** [EnesKaraosman/SwiftyChat#27]
There's a listener for `keyboardWillShowNotification`, but chat view doesn't scroll to bottom, because `isKeyboardActive` is `true`. 

<img width="1056" alt="Screenshot 2022-04-13 at 12 56 04" src="https://user-images.githubusercontent.com/1039100/163153360-d12ef304-c850-47c8-825a-7444426ce1b0.png">

Also, I couldn't find if there's functionality to scroll to bottom on message sent (nice to have, i.e. if you scrolled up while typing).

**Comment by EnesKaraosman** [comment]
I remember that we've added `isKeyboardActive` condition because the user might check an already received message and based on that he may be writing a new message. So we did not want user to loose his focus by scrolling..
