### ISSUE TITLE
Indicator to suggest when to scroll down

### ISSUE THREAD

**Issue by WilderLopez** [EnesKaraosman/SwiftyChat#3]
<img width="416" alt="Captura de Pantalla 2020-10-26 a la(s) 12 38 48 p  m" src="https://user-images.githubusercontent.com/33243719/97201041-58ef4900-1788-11eb-8403-416f39c2ad72.png">

**Comment by EnesKaraosman** [comment]
As you know in SwiftUI we do not have much support for scrolling things, for now I have to ignore this request :(

**Comment by WilderLopez** [comment]
What about `GeometryReader`? I have an natively swiftUI solution.
[ScrollViewOffset.swift.zip](https://github.com/EnesKaraosman/SwiftyChat/files/5547022/ScrollViewOffset.swift.zip)

**Comment by EnesKaraosman** [comment]
Seems not working with `List`?, Also how can we know about fullHeight so that we can calculate how much we close to bottom.
Also if you were able to get it work, we can add scrollToBottom feature for iOS13, I mean you can create Pull Request it's much appreciated :) @WilderLopez
