### ISSUE TITLE
Update WrappingHStack dependency.

### ISSUE THREAD

**Issue by irangareddy** [EnesKaraosman/SwiftyChat#32]
There was build failure with https://github.com/dkk/WrappingHStack/issues/37 issue, which now has been fixed. I would request you to look into update the WrappingHStack Dependency.

**Comment by EnesKaraosman** [comment]
Ok I upgraded and released version 2.2.1 and closing the issue. Can you check and re-open if needed

**Comment by irangareddy** [comment]
It's working! Thanks 😍
