### ISSUE TITLE
Testing performance using Instruments

### ISSUE THREAD

**Issue by WilderLopez** [EnesKaraosman/SwiftyChat#4]
I suggest that you inspect the library using Instruments, there are several issues with the performance of the cpu. I have solved one in particular, I hope you understand the importance of this work. Here is the solution that I propose:

### SwiftyChat > Styles > ChatMessageCellStyle.swift

    import SwiftUI
    import Combine
    
    public class ChatMessageCellStyle: ObservableObject {
    
       
        public let objectWillChange = ObservableObjectPublisher()
       
        ...
        
        public init(...) {
            ...
            
            objectWillChange.send()
        }
    
    }

### The error before being solved, tracked with instruments
<img width="1440" alt="Captura de Pantalla 2020-12-16 a la(s) 10 00 20 a  m" src="https://user-images.githubusercontent.com/33243719/102370483-188f9880-3f8b-11eb-8cf1-8bf1e289a30e.png">

**Comment by EnesKaraosman** [comment]
Thanks for letting me know, I'll take a closer look, by the way if you can create PR I'd like to accept it, by doing this, people see this package has contributors and kinda active, may be more people get into this.
Otherwise I can add your fix manually as well.

**Comment by EnesKaraosman** [comment]
Released your fix under version [1.3.2]. I'll keep going investigating performance problems, thanks again.
