### ISSUE TITLE
BasicInputView on tabbar

### ISSUE THREAD

**Issue by nasru** [EnesKaraosman/SwiftyChat#5]
hi. When I use tabview, BasicInputView is under the tabbar. How can I show BasicInputView on tabbar?

<img width="434" alt="Ekran Resmi 2020-12-17 00 37 34" src="https://user-images.githubusercontent.com/10481959/102409424-1156a200-4000-11eb-8cc2-c2ff2ef363f9.png">

**Comment by EnesKaraosman** [comment]
```swift
ChatView(...) {
..
}
.padding(.bottom, 1) << Here does the trick
```
The above hack fix keyboard visibility issue but, breaks keyboard specially for iOS14, this might be SwiftUI bug, not sure.
But I recommend avoid using it with `TabView` 😞 , try hiding `TabView` please visit this [link](https://github.com/TreatTrick/Hide-TabBar-In-SwiftUI)
