### ISSUE TITLE
Bottom safe area ?

### ISSUE THREAD

**Issue by WilderLopez** [EnesKaraosman/SwiftyChat#6]
shouldn't there be a default space here ?
<img width="327" alt="Captura de Pantalla 2021-01-19 a la(s) 4 23 13 p  m" src="https://user-images.githubusercontent.com/33243719/105123957-16978880-5aa7-11eb-91a9-da4e42f0ccaf.png">

**Comment by evertoncunha** [comment]
I was looking for the same thing, I'm surprised that this question has more than 1 year already

**Comment by bporter95** [comment]
Did you try adding some padding to the `ChatInputView` ?

This seemed to work for me: 
```
ChatInputView(
    ...
)
.padding(.bottom, 20)
```
