### ISSUE TITLE
scrollToBottom

### ISSUE THREAD

**Issue by seniorAyman** [EnesKaraosman/SwiftyChat#9]
hi all
when I send a new message the scroll view does not scroll to the new message at the bottom
please advise
regards

**Comment by WilderLopez** [comment]
@seniorAyman try to use it like this: `ChatView<MockMessages.ChatMessageItem, MockMessages.ChatUserItem>(messages: $messages, scrollToBottom: $scroll)`. Note that it is only available for iOS 14. Use `$scroll` as a local variable.

**Comment by seniorAyman** [comment]
@WilderLopez still the same problem , not scrolling

**Comment by WilderLopez** [comment]
@seniorAyman try with latest version 1.3.5

**Comment by seniorAyman** [comment]
@WilderLopez the same problem with version 1.3.5

**Comment by EnesKaraosman** [comment]
can you share the code you're trying.

**Comment by seniorAyman** [comment]
this is from the example and I only changed the init for ChatView

struct AdvancedExampleView: View {
    @State var messages: [MockMessages.ChatMessageItem] = []
    @State private var scrollToBottom = true
    
    @State private var message = ""
    @State private var isEditing = false
    
    var body: some View {
        NavigationView {
            chatView
        }
    }
    
    private var chatView: some View {
        ChatView<MockMessages.ChatMessageItem, MockMessages.ChatUserItem>(messages: $messages,scrollToBottom : $scrollToBottom) {

            BasicInputView(
                message: $message,
                isEditing: $isEditing,
........

**Comment by EnesKaraosman** [comment]
initially have `scrollToBottom = false` & assign `= true` when you want, and let us know the result.

**Comment by seniorAyman** [comment]
> initially have `scrollToBottom = false` & assign `= true` when you want, and let us know the result.

perfect, working fine
thanks a lot
